apiVersion: v1
kind: Secret
metadata:
  name: "#{Application.Name}#"
  namespace: "#{Application.Namespace}#"
  labels:
    name: "#{Application.Name}#"
    tribe: "#{Application.Tribe}#"
    squad: "#{Application.Squad}#"    
type: Opaque
stringData:
  TAG_APPLICATION_RELEASE_VERSION: "#{Tag.Application.Release.Version}#"

